-- phpMyAdmin SQL Dump
-- version 4.9.4
-- https://www.phpmyadmin.net/
--
-- Хост: 127.0.0.1
-- Время создания: Май 19 2022 г., 16:20
-- Версия сервера: 10.2.12-MariaDB
-- Версия PHP: 5.6.40

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `stud02_TravelBD`
--

-- --------------------------------------------------------

--
-- Структура таблицы `posts`
--

CREATE TABLE `posts` (
  `id` int(10) UNSIGNED NOT NULL,
  `content` longtext COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `img1` varchar(100) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `img2` varchar(100) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `name` varchar(200) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '',
  `parent` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  `links` varchar(200) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `header` text COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `allowed` int(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

--
-- Дамп данных таблицы `posts`
--

INSERT INTO `posts` (`id`, `content`, `img1`, `img2`, `name`, `parent`, `links`, `header`, `allowed`) VALUES
(1, '45363', NULL, NULL, 'Home', 0, NULL, 'Home', 0),
(2, 'Привет', NULL, NULL, 'News', 0, NULL, 'News', 0),
(3, '', '', '', 'Blog', 0, '', 'Blog', 0),
(4, 'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...', 'lamp-400.jpg', 'lamp-800.jpg', 'Blog', 3, '<a href=\"category.html\">Design</a><a href=\"category.html\">Photography</a>', 'Just a Standard Format Post.', 0),
(5, 'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...', 'tulips-400.jpg', 'tulips-800.jpg', 'News', 2, '<a href=\"category.html\">Health</a>', '10 Interesting Facts About Caffeine.', 0),
(6, 'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...', 'cookies-400.jpg', 'cookies-800.jpg', 'Blog', 3, '<a href=\"category.html\">Cooking</a><a href=\"category.html\">Health</a>', 'No Sugar Oatmeal Cookies.', 0),
(7, '<p class=\"lead\">Duis ex ad cupidatat tempor Excepteur cillum cupidatat fugiat nostrud cupidatat dolor sunt sint sit nisi est eu exercitation incididunt adipisicing veniam velit id fugiat enim mollit amet anim veniam dolor dolor irure velit commodo cillum sit nulla ullamco magna amet magna cupidatat qui labore cillum sit in tempor veniam consequat non laborum adipisicing aliqua ea nisi sint.</p>\r\n<p>Duis ex ad cupidatat tempor Excepteur cillum cupidatat fugiat nostrud cupidatat dolor sunt sint sit nisi est eu exercitation incididunt adipisicing veniam velit id fugiat enim mollit amet anim veniam dolor dolor irure velit commodo cillum sit nulla ullamco magna amet magna cupidatat qui labore cillum sit in tempor veniam consequat non laborum adipisicing aliqua ea nisi sint ut quis proident ullamco ut dolore culpa occaecat ut laboris in sit minim cupidatat ut dolor voluptate enim veniam consequat occaecat fugiat in adipisicing in amet Ut nulla nisi non ut enim aliqua laborum mollit quis nostrud sed sed.</p>', 'wheel-400.jpg', 'wheel-800.jpg', 'News', 2, '<a href=\"#\">Health</a><a href=\"#\">Lifestyle</a>', 'Visiting Theme Parks Improves Your Health.', 0),
(8, '<p>Harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus <a href=\"0#\">omnis voluptas assumenda est</a> id quod maxime placeat facere possimus, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et.</p>\r\n<p>Odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Nulla vitae elit libero, a pharetra augue laboris in sit minim cupidatat ut dolor voluptate enim veniam consequat occaecat fugiat in adipisicing in amet Ut nulla nisi non ut enim aliqua laborum mollit quis nostrud sed sed.</p>', 'shutterbug-400.jpg', 'shutterbug-800.jpg', 'News', 2, '<a href=\"category.html\">Family</a><a href=\"category.html\">Photography</a>', 'Key Benefits Of Family Photography.', 0),
(9, 'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...', 'fuji-400.jpg', 'fuji-800.jpg', 'News', 2, '<a href=\"category.html\">Design</a><a href=\"category.html\">Photography</a>', 'Just Another  Standard Format Post.', 0),
(10, ' Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...', 'jump-400.jpg', 'jump-800.jpg', 'Blog', 3, '<a href=\"category.html\">Family</a><a href=\"category.html\">Relationship</a>', 'Create Meaningful Family Moments.', 0),
(11, 'Ниагарский водопад состоит из трёх больших потоков: Хорсшу-Фолс («Подкова»), Американский водопад и Брайдлвей («Фата»). Пользуется большой популярностью среди туристов (во многом из-за развитой инфраструктуры). Это не самый высокий водопад, порядка 53 метров, однако один из самых мощных — объём падающей воды достигает 5 700 м³/с.', 'neogar.jpg', '', 'Canada', 15, '', 'Ниагарский водопад', 0),
(12, 'Голубая лагуна — геотермальный спа-курорт всего в 40 км от Рейкьявика. Это место появилось не само собой, а во многом благодаря человеку: вода с электростанций, снабжающих энергией столицу, скопилась на лавовом плато. В результате в воде появились минеральные соли, кремнезём и сине-зелёные водоросли, что придало ей лечебные свойства.', 'bluLaguna.jpg', '', 'Iceland', 15, '', 'Голубая лагуна', 0),
(13, 'Другое название — «Небесные врата». Это самая высокая пещера, она образовалась в 263 году, когда внезапно большой кусок горы просто отвалился, создав огромную полость. К её подножию ведёт 999 ступеней: по легенде, пройдя по ним, можно достигнуть просветления и приблизиться к Богу. Такое под силу не каждому, а в Китае, видимо, не любят разочаровывать туристов, поэтому сделали самый длинный в мире фуникулёр и самый высокий открытый лифт. Над пещерой почти всегда можно наблюдать облако тумана, что придаёт ей ещё больше таинственности.', 'Gates.jpg', '', 'China', 15, '', 'Paradise Gates', 0),
(14, 'Ледниковое озеро в провинции Альберта в Канаде. Оно окружено Скалистыми горами, вершины которых круглый год покрыты снегом, а склоны — вечнозелёными лесами. Это место для активного отдыха: пеших, конных и велосипедных прогулок, гольфа, тенниса, горнолыжного спорта, альпинизма и катания на собачьих упряжках.', 'Luiz.jpg', '', 'Canada', 15, '', 'Озеро Луиз', 0),
(15, '', '', '', 'Cities', 0, '', 'Cities', 1),
(16, 'Возможно, вы уже слышали о знаменитом ледяном отеле в Квебеке. Считается, что это одно из самых романтичных мест на планете, поэтому сотни (если не тысячи) пар ежегодно приезжают сюда, чтобы сочетаться браком. Он целиком сделан из 20 тонн снега и льда. Каждый год в декабре его начинают перестраивать, чтобы в начале января принимать первых гостей. Которым, кстати, перед заселением проводят инструктаж, как не получить обморожение во время проживания в отеле.', 'Icehotel.jpg', '', 'Canada', 15, '', 'Отель-де-Глас', 0),
(17, 'Северное сияние — удивительное природное явление: чтобы вы могли увидеть его на Земле, на Солнце должен произойти взрыв. Исландия — прекрасное место, чтобы увидеть северное сияние, но далеко не единственное. В некоторых регионах России вы также можете полюбоваться этим феноменом.', 'NorthLight.jpg', '', 'Iceland', 15, '', 'North Light', 0),
(18, 'Самое чистое и самое глубокое озеро планеты. Объём воды в Байкале — около 23 000 км³, что составляет 20% мировых и 90% российских запасов пресной воды. И, конечно, это одно из самых красивых мест, которое только можно представить. Поэтому Байкал так любят и так им гордятся жители нашей страны. Начать своё исследование 100 самых красивых мест планеты стоит именно с Байкала.', 'Baikal.jpg', '', 'Russia', 15, '', 'Lake Baikal', 0),
(19, 'Яркий сапфировый свет в пещере появился из-за того, что в течение столетий лёд спрессовывался, вытесняя воздушные пузыри. Так как кислорода не осталось, лёд поглощает солнечный свет и переливается оттенками синего. В целях безопасности путешественникам можно посещать Скафтафелл только при низкой температуре воздуха.', 'Skaftafell.jpg', '', 'Iceland', 15, '', 'Skaftafell Cave', 0),
(20, 'Для поездки на Соловки трёх-четырёх дней недостаточно — столько здесь достопримечательностей, памятников древней архитектуры, которые стоит увидеть. Рекомендуем обязательно посетить Соловецкий монастырь, побывать на мысе Белужском и понаблюдать за белухами, которые похожи на дельфинов-альбиносов, съездить к соловецким скитам, увидеть загадочные лабиринты на мысе Лабиринтов. Добраться на Соловки непросто, но это того стоит.', 'Solovki.jpg', '', 'Russia', 15, '', 'Solovki', 0),
(21, 'Гора Тяньцзы является одной из четырёх самых известных живописных зон заповедника Улинъюань. Вершина Тяньцзы находится в середине «золотого треугольника» на высоте 1 260 метров. Это место прекрасных водопадов, таинственных пещер, живописных лесов и богатого животного мира. Для тех, кто боится самостоятельно преодолеть путь через леса, есть канатные трамваи. На них можно быстро подняться на вершину горы.', 'MountTianczi.jpg', '', 'China', 15, '', 'Mount Tianzi', 0),
(22, 'Великая Китайская стена — это один из самых масштабных и самых древних памятников архитектуры. Её длина составляет почти 9 тысяч километров — размеры действительно впечатляют. Ко всему прочему, это одна из самых посещаемых достопримечательностей в мире: ежегодно здесь бывает около 40 миллионов туристов.', 'ChinaWall.jpg', '', 'China', 15, '', 'The great Wall of China', 0),
(23, 'Крупнейший архипелаг Белого моря известен не только своей историей и архитектурными достопримечательностями, но и удивительной природой. Соловецкие острова состоят из шести крупных островов и сотни маленьких. Самый крупный из них Большой Соловецкий остров, на котором и расположен духовный центр этого региона — Спасо‑Преображенский Соловецкий монастырь, возведённый ещё в XV веке.\r\n<p>Природа Соловков уникальна: здесь можно прогуляться по заповедному хвойному лесу, познакомиться с нерпами, белухами и морскими зайцами, а после заката увидеть северное сияние. Красотой поражают и множественные озёра с пресной водой, а погода тут более чем комфортная, особенно летом.</p>', 'SolovIlands.jpg', '', 'Russia', 15, '', 'Solovetsky Islands', 0),
(24, '<p>Odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa.</p>\r\n<ul>\r\n<li>Donec nulla non metus auctor fringilla.\r\n<ul>\r\n<li>Lorem ipsum dolor sit amet.</li>\r\n<li>Lorem ipsum dolor sit amet.</li>\r\n<li>Lorem ipsum dolor sit amet.</li>\r\n</ul>\r\n</li>\r\n<li>Donec nulla non metus auctor fringilla.</li>\r\n<li>Donec nulla non metus auctor fringilla.</li>\r\n</ul>\r\n<p>Odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Nulla vitae elit libero, a pharetra augue laboris in sit minim cupidatat ut dolor voluptate enim veniam consequat occaecat fugiat in adipisicing in amet Ut nulla nisi non ut enim aliqua laborum mollit quis nostrud sed sed.</p>', 'guitarman-400.jpg', 'guitarman-800.jpg', 'News', 2, '<a href=\"category.html\">Music</a>\r\n<a href=\"category.html\">Lifestyle</a>', 'What Your Music Preference Says About You and Your Personality.', 0),
(25, 'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...', 'beetle-400.jpg', 'beetle-800.jpg', 'Blog', 3, '<a href=\"category.html\">Lifestyle</a>', 'Throwback To The Good Old Days.', 0),
(26, 'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...', 'sydney-400.jpg', 'sydney-800.jpg', 'Blog', 3, '<a href=\"category.html\">Travel</a>\r\n<a href=\"category.html\">Vacation</a>', 'Planning Your First Trip to Sydney.', 0),
(27, '', '', '', 'Categories', 0, '', 'Categories', 1),
(28, '', '', '', 'Sport & Health', 27, '', 'Вершины, которые нужно успеть покорить', 0),
(29, '<p>Эльбрус, самая высокая вершина не только России, но и Европы, на самом деле состоит из двух спящих вулканов, и с ее западной стороны виден хорошо сохранившийся вулканический кратер шириной 250 метров. Гора Эльбрус популярна среди новичков и известна своими сложным, но в то же время захватывающим маршрутом. Восхождение на вершину на высоте 5 642 метра занимает около недели.</p>\r\n<article class=\"row format-standard\">\r\n<div class=\"s-content__header col-full\">\r\n<a href=\"/Categories/Sport & Health\" class=\"entry__thumb-link\">\r\n<img class=\"cityImg\" src=\"/images/Sport & Health/Capsula.jpg\">\r\n</a>\r\n</div>\r\n</article>\r\n<p>\r\n<a href=\"https://www.booking.com/hotel/ru/eko-leaprus.ru.html?aid=356980&label=gog235jc-1DEghhcnRpY2xlcyiCAjjoB0ghWANowgGIAQGYASG4ARfIAQzYAQPoAQH4AQKIAgGoAgO4ApLCh5QGwAIB0gIkMjZhMTM2ZTAtNTE5Yy00YTI3LThkMGQtNmQ4Y2JmYzg4Y2Yy2AIE4AIB&sid=4f2d2ccae5bfad42bdbd59f718afaa10&dist=0&sb_price_type=total&type=total&\">Капсульный отель LeapRus</a> — уникальный вариант размещения прямо на вершине. Здесь вы сможете насладиться всевозможными видами досуга в горах.\r\n</p>', 'Ellbrus.jpg', 'Capsula.jpg', 'Sport & Health', 27, '', 'Эльбрус, Россия', 0),
(30, '<p>Килиманджаро высотой 5 899 метров — высочайшая гора в Африке и одна из самых знаменитых вершин в мире. Несмотря на то, что восхождение на Килиманджаро никак нельзя назвать легким, здесь вы найдете различные маршруты для новичков. Таким образом начинающие альпинисты смогут привыкнуть к изменениям состояния организма с увеличением высоты и не волноваться о технических трудностях или климатических условиях. Вне независимости от опыта все путешественники должны подниматься в сопровождении местного гида и рассчитывать, что восхождение займет от 5 до 6 дней. Это того стоит, так как на вершине вам откроется потрясающий и неповторимый вид.</p>\r\n<article class=\"row format-standard\">\r\n<div class=\"s-content__header col-full\">\r\n<a href=\"/Categories/Sport & Health\" class=\"entry__thumb-link\">\r\n<img class=\"cityImg\" src=\"/images/Sport & Health/Kaliwa.jpg\">\r\n</a>\r\n</div>\r\n</article>\r\n<p>\r\nИз комплекса <a href=\"https://www.booking.com/hotel/tz/kaliwa-lodge.ru.html?aid=356980&label=gog235jc-1DEghhcnRpY2xlcyiCAjjoB0ghWANowgGIAQGYASG4ARfIAQzYAQPoAQH4AQKIAgGoAgO4ApLCh5QGwAIB0gIkMjZhMTM2ZTAtNTE5Yy00YTI3LThkMGQtNmQ4Y2JmYzg4Y2Yy2AIE4AIB&sid=4f2d2ccae5bfad42bdbd59f718afaa10&dist=0&sb_price_type=total&type=total&\">Kaliwa Lodge</a> у подножия Килиманджаро открывается прекрасный вид на горы, а всего в нескольких минутах от комплекса находится вход в Национальный парк Килиманджаро.\r\n</p>', 'Kilimanjaro.jpg', 'Kaliwa.jpg', 'Sport & Health', 27, '', 'Килиманджаро, Танзания', 0),
(31, '<p>Гора <a href\"https://www.booking.com/city/us/denali-national-park.ru.html?aid=356980&label=gog235jc-1DEghhcnRpY2xlcyiCAjjoB0ghWANowgGIAQGYASG4ARfIAQzYAQPoAQH4AQKIAgGoAgO4ApLCh5QGwAIB0gIkMjZhMTM2ZTAtNTE5Yy00YTI3LThkMGQtNmQ4Y2JmYzg4Y2Yy2AIE4AIB&sid=4f2d2ccae5bfad42bdbd59f718afaa10&inac=0&\">Денали</a> (также известная как Мак-Кинли) расположена в Национальном парке Денали и является самой высокой вершиной в Северной Америке (ее высота составляет 6 194 метра). Нет ничего удивительного в том, что маршрут здесь предполагает намного более крутой подъем, и даже опытным альпинистам может пригодиться помощь одной из шести зарегистрированных в парке туристических компаний. На Денали лучше всего подниматься в период с мая по июнь. В это время устанавливаются наиболее стабильные погодные условия и прохождение по всему маршруту занимает до четырех недель.</p>\r\n<article class=\"row format-standard\">\r\n<div class=\"s-content__header col-full\">\r\n<a href=\"/Categories/Sport & Health\" class=\"entry__thumb-link\">\r\n<img class=\"cityImg\" src=\"/images/Sport & Health/McKinley.jpg\">\r\n</a>\r\n</div>\r\n</article>\r\n<p>Недалеко от комплекса <a href=\"https://www.booking.com/hotel/us/mckinley-creekside-cabins.ru.html?aid=356980&label=gog235jc-1DEghhcnRpY2xlcyiCAjjoB0ghWANowgGIAQGYASG4ARfIAQzYAQPoAQH4AQKIAgGoAgO4ApLCh5QGwAIB0gIkMjZhMTM2ZTAtNTE5Yy00YTI3LThkMGQtNmQ4Y2JmYzg4Y2Yy2AIE4AIB&sid=4f2d2ccae5bfad42bdbd59f718afaa10&dist=0&sb_price_type=total&type=total&\">McKinley Creekside Cabins</a> есть несколько пешеходных троп, по которым можно пройти в свободное от восхождения на вершину время.</p>', 'Denali.jpg', 'McKinley.jpg', 'Sport & Health', 27, '', 'Денали, Аляска', 0),
(32, 'Мааттерхорн со своей почти идеальной формой пирамиды и обособленным расположением стала одной из самых часто фотографируемых вершин в мире и вошла в списки для покорения многих альпинистов. Чтобы взойти на вершину высотой 4 478 метров, вам понадобится два дня, а также потребуется помощь проводника.\r\n<article class=\"row format-standard\">\r\n<div class=\"s-content__header col-full\">\r\n<a href=\"/Categories/Sport & Health\" class=\"entry__thumb-link\">\r\n<img class=\"cityImg\" src=\"/images/Sport & Health/Patricia.jpg\">\r\n</a>\r\n</div>\r\n</article>\r\n<p>Вершина Мааттерхорн видна из многих городов, но чтобы насладиться ее самыми знаменитыми видами, отправляйтесь в <a href=\"https://www.booking.com/city/ch/zermatt.ru.html?aid=356980&label=gog235jc-1DEghhcnRpY2xlcyiCAjjoB0ghWANowgGIAQGYASG4ARfIAQzYAQPoAQH4AQKIAgGoAgO4ApLCh5QGwAIB0gIkMjZhMTM2ZTAtNTE5Yy00YTI3LThkMGQtNmQ4Y2JmYzg4Y2Yy2AIE4AIB&sid=4f2d2ccae5bfad42bdbd59f718afaa10&inac=0&\">Церматт</a>. К услугам гостей в <a href=\"https://www.booking.com/hotel/ch/residence-patricia.ru.html?aid=356980&label=gog235jc-1DEghhcnRpY2xlcyiCAjjoB0ghWANowgGIAQGYASG4ARfIAQzYAQPoAQH4AQKIAgGoAgO4ApLCh5QGwAIB0gIkMjZhMTM2ZTAtNTE5Yy00YTI3LThkMGQtNmQ4Y2JmYzg4Y2Yy2AIE4AIB&sid=4f2d2ccae5bfad42bdbd59f718afaa10&dist=0&sb_price_type=total&type=total&\">комплексе Residence Patricia</a> апартаменты с обслуживанием, во многих из них есть балконы, откуда можно сделать потрясающие фотографии вершины.</p>', 'Maatterhorn.jpg', 'Patricia.jpg', 'Sport & Health', 27, '', 'Мааттерхорн, Швейцария', 0),
(33, '', '', '', 'Travel with Family', 27, '', 'Летние пешие походы в Альпах для всей семьи', 1),
(34, 'Альпийское озеро Эшинензе, вдоль берега которого пролегают несколько пешеходных троп, считается самым красивым альпийским озером в Швейцарии. Вода в Эшинензе поступает из ледника Фрюнден, и летом голубая гладь озера мерцает в лучах солнца. Открыточный швейцарский пейзаж вокруг Эшинензе изрезан лабиринтом тихих пешеходных троп. У озера есть сайт с картой большинства маршрутов, и туристы любого уровня подготовки могут выбрать подходящую для себя тропу.\r\n\r\nК началу маршрутов можно добраться из небольшого городка <a href=\"https://www.booking.com/city/ch/kandersteg.ru.html?aid=356980&label=gog235jc-1DEghhcnRpY2xlcyiCAjjoB0ghWANowgGIAQGYASG4ARfIAQzYAQPoAQH4AQKIAgGoAgO4ApLCh5QGwAIB0gIkMjZhMTM2ZTAtNTE5Yy00YTI3LThkMGQtNmQ4Y2JmYzg4Y2Yy2AIE4AIB&sid=4f2d2ccae5bfad42bdbd59f718afaa10\">Кандерштег</a> на гондольном подъемнике, курсирующем к озеру. От верхней станции подъемника до озера можно дойти за 25 минут по хорошо протоптанной грунтовой тропе. Держите фотоаппарат наготове, чтобы запечатлеть тот неповторимый момент, когда вам впервые откроется вид на бирюзовую гладь озера, окруженного скалистыми отрогами горы Дольденхорн. Вода в озере даже летом бывает довольно прохладной для купания, но это не мешает местным жителям прыгать в него бомбочкой. Если плавание не входит в ваши планы, отправляйтесь в поход по холмистым лугам и горным перевалам, мимо водопадов, переходя вброд тихие ручейки.\r\n\r\nВернувшись к гондольному подъемнику, непременно посетите главный местный аттракцион — Родельбан Эшинензе. Эта летняя санная трасса длиной 750 метров вниз по крутому склону горы гарантирует всплеск адреналина как детям, так и взрослым. Держитесь крепче на крутых поворотах, проносясь мимо озерных пейзажей. К счастью, скорость саней всегда можно контролировать. Накатавшись вдоволь, возвращайтесь в Кандерштег и отдохните в <a href=\"https://www.booking.com/hotel/ch/landgasthof-ruedihus.ru.html?aid=356980&label=gog235jc-1DEghhcnRpY2xlcyiCAjjoB0ghWANowgGIAQGYASG4ARfIAQzYAQPoAQH4AQKIAgGoAgO4ApLCh5QGwAIB0gIkMjZhMTM2ZTAtNTE5Yy00YTI3LThkMGQtNmQ4Y2JmYzg4Y2Yy2AIE4AIB&sid=4f2d2ccae5bfad42bdbd59f718afaa10\">Landgasthof Ruedihus</a>, традиционном альпийском шале с террасой для солнечных ванн и ухоженным садом.', 'Eshinenze.jpg', '', 'Travel with Family', 27, '', 'Эшинензе, Швейцария', 0),
(35, 'Это место подойдет для семей, у которых чуть больше опыта в пеших походах. В городке <a href=\"https://www.booking.com/city/fr/chamonix-mont-blanc.ru.html?aid=356980&label=gog235jc-1DEghhcnRpY2xlcyiCAjjoB0ghWANowgGIAQGYASG4ARfIAQzYAQPoAQH4AQKIAgGoAgO4ApLCh5QGwAIB0gIkMjZhMTM2ZTAtNTE5Yy00YTI3LThkMGQtNmQ4Y2JmYzg4Y2Yy2AIE4AIB&sid=4f2d2ccae5bfad42bdbd59f718afaa10\">Шамони</a>, расположенном во Французских Альпах, берут начало многочисленные пешеходные тропы по окрестностям Монблана. В тени этой могучей горы проходят сложные маршруты, которые не дадут вам расслабиться, но ни с чем не сравнимые виды на самую высокую вершину Западной Европы подарят вам силы. Если у вашей семьи большой опыт походов и жизни в палатках, подумайте, не решиться ли на 11-дневный поход по маршруту Шамони-Монблан длиной 170 километров. В этом походе вы сможете обойти вокруг Монблана и вдоволь понежиться в лучах летнего солнца.\r\n\r\nЕсли вы сомневаетесь в своих силах, вы можете ограничиться отдельным отрезком маршрута или разбить его на несколько этапов. Например, вы можете провести пару дней на первых двух участках маршрута или за один день преодолеть его первый этап, из Шамони в Лез-Уш. По дороге найдется жилье, где рады большим семьям. Окунитесь в мир мюзикла «Звуки музыки», гуляя по усеянным полевыми цветами лугам и ароматным сосновым лесам. И передавайте привет стадам горных козликов! В этом районе полно живописных кемпингов, но если вы предпочитаете останавливаться с комфортом, вам может подойти традиционный французский горный отель, такой как <a href=\"https://www.booking.com/hotel/fr/refuge-du-montenvers.ru.html?aid=356980&label=gog235jc-1DEghhcnRpY2xlcyiCAjjoB0ghWANowgGIAQGYASG4ARfIAQzYAQPoAQH4AQKIAgGoAgO4ApLCh5QGwAIB0gIkMjZhMTM2ZTAtNTE5Yy00YTI3LThkMGQtNmQ4Y2JmYzg4Y2Yy2AIE4AIB&sid=4f2d2ccae5bfad42bdbd59f718afaa10\">Refuge du Montenvers</a>. Здесь вы в полной мере сможете насладиться настоящим альпийским отдыхом.', 'Shamoni.jpg', '', 'Travel with Family', 27, '', 'Шамони, Франция', 0),
(36, '', '', '', 'Food & Drink', 27, '', 'Лучшие города для путешественников-веганов', 1),
(37, '<a href=\"https://www.booking.com/city/il/tel-aviv.ru.html?aid=356980&label=gog235jc-1DEghhcnRpY2xlcyiCAjjoB0ghWANowgGIAQGYASG4ARfIAQzYAQPoAQH4AQKIAgGoAgO4ApLCh5QGwAIB0gIkMjZhMTM2ZTAtNTE5Yy00YTI3LThkMGQtNmQ4Y2JmYzg4Y2Yy2AIE4AIB&sid=4f2d2ccae5bfad42bdbd59f718afaa10\">Тель-Авив</a> — это рай для путешественников-веганов, где нут и тхина составляют основу большого числа популярных местных блюд. Многие основные веганские блюда родом с Ближнего Востока, тогда как в Израиле можно попробовать один из лучших <a href=\"https://www.booking.com/articles/around-the-world-in-falafel.ru.html?aid=356980&label=gog235jc-1DEghhcnRpY2xlcyiCAjjoB0ghWANowgGIAQGYASG4ARfIAQzYAQPoAQH4AQKIAgGoAgO4ApLCh5QGwAIB0gIkMjZhMTM2ZTAtNTE5Yy00YTI3LThkMGQtNmQ4Y2JmYzg4Y2Yy2AIE4AIB&sid=4f2d2ccae5bfad42bdbd59f718afaa10\">фалафелей</a> с хумусом в мире. Здесь его подают теплым и зачастую с ломтиком хрустящего свежего лука. Всего одной тарелки этого блюда с неземным вкусом, подаваемого с горячей воздушной питой, будет достаточно, чтобы сытно поесть. Кроме того, веганов на душу населения в Израиле больше, чем в любой другой стране, поэтому здесь у туристов, придерживающихся растительной диеты, есть широкий выбор ресторанов на любой вкус. Кафе Anastasia, одна из первых веганских закусочных в Тель-Авиве, производит собственное соевое, миндальное и рисовое молоко, а ресторан The Green Cat гордится тем, что является первой на 100% веганской пиццерией в Тель-Авиве (сыр здесь делают из кешью). <a href=\"https://www.booking.com/hotel/il/the-norman-tel-aviv-tel-aviv.ru.html?aid=356980&label=gog235jc-1DEghhcnRpY2xlcyiCAjjoB0ghWANowgGIAQGYASG4ARfIAQzYAQPoAQH4AQKIAgGoAgO4ApLCh5QGwAIB0gIkMjZhMTM2ZTAtNTE5Yy00YTI3LThkMGQtNmQ4Y2JmYzg4Y2Yy2AIE4AIB&sid=4f2d2ccae5bfad42bdbd59f718afaa10\">The Norman Tel Aviv</a> — это бутик-отель, в ресторанах которого подают вкусные и потрясающе оформленные веганские блюда.', 'Falafel.jpg', '', 'Food & Drink', 27, '', 'Тель-Авив, Израиль', 0),
(38, 'Тайвань — настоящий праздник для всех гурманов, при этом он особенно привлекателен для веганов, поскольку здесь не так широко используются молочные продукты, а распространенность вегетарианства объясняется большим числом буддистов в стране. В столице <a href=\"https://www.booking.com/city/tw/t-ai-pei.ru.html?aid=356980&label=gog235jc-1DEghhcnRpY2xlcyiCAjjoB0ghWANowgGIAQGYASG4ARfIAQzYAQPoAQH4AQKIAgGoAgO4ApLCh5QGwAIB0gIkMjZhMTM2ZTAtNTE5Yy00YTI3LThkMGQtNmQ4Y2JmYzg4Y2Yy2AIE4AIB&sid=4f2d2ccae5bfad42bdbd59f718afaa10\">Тайбэе</a> полно восхитительной веганской уличной еды. Обязательно попробуйте хрустящие блины с зеленым луком, свежие пельмени, приготовленные на пару, наваристые бульоны мисо с лапшой и популярный местный вонючий тофу. Рисовая каша, димсам с бархатистым насыщенным грибным вкусом, а также другие веганские блюда в отеле <a href=\"https://www.booking.com/hotel/tw/mandarin-oriental-taipei.ru.html?aid=356980&label=gog235jc-1DEghhcnRpY2xlcyiCAjjoB0ghWANowgGIAQGYASG4ARfIAQzYAQPoAQH4AQKIAgGoAgO4ApLCh5QGwAIB0gIkMjZhMTM2ZTAtNTE5Yy00YTI3LThkMGQtNmQ4Y2JmYzg4Y2Yy2AIE4AIB&sid=4f2d2ccae5bfad42bdbd59f718afaa10\">Mandarin Oriental Taipei</a> настолько аппетитны, что вы непременно попросите добавки.', 'Tofu.jpg', '', 'Food & Drink', 27, '', 'Тайбэй, Тайвань', 0),
(39, '<p href=\"https://www.booking.com/city/us/los-angeles.ru.html?aid=356980&label=gog235jc-1DEghhcnRpY2xlcyiCAjjoB0ghWANowgGIAQGYASG4ARfIAQzYAQPoAQH4AQKIAgGoAgO4ApLCh5QGwAIB0gIkMjZhMTM2ZTAtNTE5Yy00YTI3LThkMGQtNmQ4Y2JmYzg4Y2Yy2AIE4AIB&sid=4f2d2ccae5bfad42bdbd59f718afaa10\">Лос-Анджелес</a>, славящийся несметным количеством зеленых соков и салатов, а также своей любовью к йоге и здоровому образу жизни, — самый дружелюбный к веганам город в США. Лос-Анджелес изобилует веганскими закусочными, от элитных ресторанов до точек быстрого питания, которые предлагают интернациональную кухню на любой вкус. Меню веганского японского ресторана Shojin состоит из овощей, риса, тофу и темпе в таких блюдах, как хрустящая темпура из грибов с трюфельной солью и, конечно же, суши. В Лос-Анджелесе также есть множество веганских тайских, вьетнамских, эфиопских, итальянских и мексиканских заведений и даже рестораны, где готовят растительные варианты классических каджунских блюд, таких как гамбо. Любители веганского фастфуда могут попробовать гамбургеры в Monty\'s и VowBurger или сладости, приготовленные без продуктов животного происхождения, в пекарнях, таких как Erin McKenna\'s Bakery. Остановитесь в стильном <a href=\"https://www.booking.com/hotel/us/mama-shelter-la.ru.html?aid=356980&label=gog235jc-1DEghhcnRpY2xlcyiCAjjoB0ghWANowgGIAQGYASG4ARfIAQzYAQPoAQH4AQKIAgGoAgO4ApLCh5QGwAIB0gIkMjZhMTM2ZTAtNTE5Yy00YTI3LThkMGQtNmQ4Y2JmYzg4Y2Yy2AIE4AIB&sid=4f2d2ccae5bfad42bdbd59f718afaa10\">отеле Mama Shelter</a> и поужинайте в отмеченном наградами веганском ресторане на крыше.', 'Shelter.jpg', '', 'Food & Drink', 27, '', 'Лос-Анджелес, США', 0),
(40, '', '', '', 'Seasons', 0, '', 'Seasons', 1),
(41, 'Посетить логово Дракулы, когда светит солнце и на полях пасутся овечки, не удастся, не так ли? Стоит взглянуть на свинцово-серое небо, голые деревья и тонкий слой снега вокруг. Брашов и Сигишоара разделены двумя часами езды на поезде и представляют собой великолепные средневековые города, которые во многом связаны с Владом Цепешем, известным как Дракула. Хотя и нет достоверных доказательств, что он когда-либо бывал в своём (так называемом) замке.', 'Transelvania.jpg', '', 'Winter', 40, '', 'Трансильвания, Румыния', 0),
(42, 'Невероятно красива весенняя Чехия. Изумительно выглядят узкие мощеные улочки, устеленные мартовским туманом. В это время воздух прозрачен, улицы сияют какой-то особенной чистотой. Ранняя весна – идеальная пора для размеренного семейного отдыха. Ближе к лету в стране начинается сезон фестивалей и ярмарок (фестиваль академической музыки «Пражская весна», фестиваль чешского кино). Праздничная суматоха придется по вкусу активной молодежи.', 'Praha.jpg', '', 'Spring', 40, '', 'Чехия', 0),
(43, '<a href=\"/tours/marokko.html\">Марокко</a> - африканская жемчужина морского отдыха. Сами названия Марракеш, Танжер, Касабланка несут на себе магическое очарования восточных странствий. Отдых в Марокко это белоснежные здания, огромные пальмы, пляжи с чистейшим песком и колорит древних арабских городов, историческая часть которых не менялась со времен средневековья.', 'Marokko.jpg', '', 'Summer', 40, '', 'Марокко', 0),
(102, 'rhrhht', '', '', 'shrshsrh', 0, NULL, 'gwrjkig', 1),
(103, 'fwqfw', '', '', 'wqefwf', 102, NULL, 'd', 1),
(104, 'egeew', '', '', 'gee', 102, NULL, 'rgeg', 1);

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `posts`
--
ALTER TABLE `posts`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT для сохранённых таблиц
--

--
-- AUTO_INCREMENT для таблицы `posts`
--
ALTER TABLE `posts`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=105;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
